spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://dinomikdb.c1f6bazer7d7.us-east-1.rds.amazonaws.com:3306/dinomikUAT?useSSL=false
    username: admin
    password: Lachocalad.1309
    driver-class-name: com.mysql.jdbc.Driver

#    #url: jdbc:mysql://localhost:3306/dinomik?useSSL=false
#    url: jdbc:mysql://localhost:3306/dinomik?useSSL=false
#    #username: mertkan
#    username: root
#    password: lachocalad11


security:
  oauth2:
    client:
      client-id: admin-client
      client-secret: mert-secret
      access-token-uri: http://localhost:8080/oauth/token




#
#security:
#  oauth2:
#    client:
#      client-id: 647358105696445
#      client-secret: 7c2cfc030acf8551641f65c2531ab0c3
#      access-token-uri: https://graph.facebook.com/oauth/access_token
#      token-name: oauth_token
#      user-authorization-uri: https://www.facebook.com/dialog/oauth
#      client-authentication-scheme: form
#      authentication-scheme: query
#    resource:
#      user-info-uri: https://graph.facebook.com/me

facebook:
  client:
    clientId: 647358105696445
    clientSecret: 7c2cfc030acf8551641f65c2531ab0c3
    accessTokenUri: https://graph.facebook.com/oauth/v3.2/access_token
    userAuthorizationUri: https://www.facebook.com/v3.2/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.hibernate: warn
    org.springframework.web: warn
    org.springframework.security: warn

file:
  artist-upload-dir: C:/DEV/dinomik/images/artists
  event-upload-dir: C:/DEV/dinomik/images/events
  user-upload-dir: C:/DEV/dinomik/images/users
  venue-upload-dir: C:/DEV/dinomik/images/venues
server:
  port: 6060
