spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/dinomik?useSSL=false
    username: mertkan
    password: lachocalad11
    driver-class-name: com.mysql.jdbc.Driver

#
#security:
#  oauth2:
#    client:
#      client-id: 647358105696445
#      client-secret: 7c2cfc030acf8551641f65c2531ab0c3
#      access-token-uri: https://graph.facebook.com/oauth/access_token
#      token-name: oauth_token
#      user-authorization-uri: https://www.facebook.com/dialog/oauth
#      client-authentication-scheme: form
#      authentication-scheme: query
#    resource:
#      user-info-uri: https://graph.facebook.com/me

facebook:
  client:
    clientId: 647358105696445
    clientSecret: 7c2cfc030acf8551641f65c2531ab0c3
    accessTokenUri: https://graph.facebook.com/oauth/v3.2/access_token
    userAuthorizationUri: https://www.facebook.com/v3.2/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.hibernate: warn
    org.springframework.web: warn
    org.springframework.security: warn
