spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mertdev01?useSSL=false
    username: root
    password: lachocalad11
    driver-class-name: com.mysql.jdbc.Driver


security:
  oauth2:
    client:
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      access-token-uri: https://graph.facebook.com/oauth/access_token
      user-authorization-uri: https://www.facebook.com/dialog/oauth
      client-secret: 7c2cfc030acf8551641f65c2531ab0c3
      client-id: 647358105696445
    resource:
      userInfoUri: https://graph.facebook.com/me

logging:
  pattern:
    console:
      file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.hibernate: warn
    org.springframework.web: warn
    org.springframework.security: warn
    com.mertkan.eventproject.controllers : warn

