spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/dinomik?useSSL=false
    username: mertkan
    password: lachocalad11
    driver-class-name: com.mysql.jdbc.Driver


security:
  oauth2:
    client:
      id: 647358105696445
      client-secret: 7c2cfc030acf8551641f65c2531ab0c3
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
        userInfoUri: https://graph.facebook.com/me


logging:
  pattern:
    console:
      file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.hibernate: debug
    org.springframework.web: warn

