logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.hibernate: warn
    org.springframework.web: warn
    org.springframework.security: warn


spring:
  profiles:
    active: "dev"
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 100MB

server:
  port: 6060

---
spring:
  profiles: dev
  datasource:
#    url: jdbc:mysql://dinomikdb.c1f6bazer7d7.us-east-1.rds.amazonaws.com:3306/dinomikDEV?useSSL=false
#    username: admin
#    password: Lachocalad.1309

    #url: jdbc:mysql://localhost:3306/dinomik?useSSL=false
    url: jdbc:mysql://localhost:3306/dinomik?useSSL=false
    #username: mertkan
    username: root
    password: lachocalad11
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: true



file:
  artist-upload-dir: C:/DEV/dinomik/images/artists
  event-upload-dir: C:/DEV/dinomik/images/events
  user-upload-dir: C:/DEV/dinomik/images/users
  venue-upload-dir: C:/DEV/dinomik/images/venues


security:
  oauth2:
    client:
      client-id: admin-client
      client-secret: mert-secret
      access-token-uri: http://localhost:8080/oauth/token

---
spring:
  profiles: uat

  datasource:
    url: jdbc:mysql://dinomikdb.c1f6bazer7d7.us-east-1.rds.amazonaws.com:3306/dinomikUAT?useSSL=false
    username: admin
    password: Lachocalad.1309
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

file:
  artist-upload-dir: /home/ubuntu/dinomik/images/artists
  event-upload-dir: /home/ubuntu/dinomik/images/events
  user-upload-dir: /home/ubuntu/dinomik/images/users
  venue-upload-dir: /home/ubuntu/dinomik/images/venues



#    #url: jdbc:mysql://localhost:3306/dinomik?useSSL=false
#    url: jdbc:mysql://localhost:3306/dinomik?useSSL=false
#    #username: mertkan
#    username: root
#    password: lachocalad11
