-- INSERT INTO USER_ (ID, EMAIL, USERNAME, PASSWORD) VALUES (1, 'admin@email.com', 'admin', 'admin1');
-- INSERT INTO ROLE (ROLE_ID, ROLE) VALUES (1, 'ADMIN');
-- INSERT INTO ROLE (ROLE_ID, ROLE) VALUES (2, 'USER');
-- INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
-- INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 2);

INSERT INTO ARTIST(ID, NAME) VALUES (1, 'Tarkan');
INSERT INTO ARTIST (ID, NAME) VALUES (2, 'Sıla');
INSERT INTO ARTIST (ID, NAME) VALUES (3, 'Kenan Doğulu');
INSERT INTO ARTIST (ID, NAME) VALUES (4, 'Ezhel');
INSERT INTO ARTIST (ID, NAME) VALUES (5, 'Mehmet Erdem');
INSERT INTO ARTIST (ID, NAME) VALUES (6, 'Manga');
INSERT INTO VENUE (ID, NAME, ADDRESS, LATITUDE, LONGITUDE) VALUES (1, 'Harbiye Cemil Topuzlu Açık Hava Tiyatrosu', 'Nişantaşı, Harbiye Mahallesi, 34367 Şişli/İstanbul', 41.046053, 28.990041 );
INSERT INTO EVENT (ID, NAME, DATE, TIME, VENUE_ID) VALUES (1, 'Tarkan', '2019-08-12', '20:00' , 1);
INSERT INTO EVENT (ID, NAME, DATE, TIME, VENUE_ID) VALUES (2, 'Sıla', '2019-08-12', '19:30' , 1);
INSERT INTO EVENT_ARTIST (ARTIST_ID, EVENT_ID) VALUES (1, 1);
INSERT INTO EVENT_ARTIST (ARTIST_ID, EVENT_ID) VALUES (2, 2);



