INSERT INTO USER_ (ID, EMAIL, USERNAME, PASSWORD) VALUES (1, 'admin@email.com', 'admin', 'admin1');
INSERT INTO ROLE (ROLE_ID, ROLE) VALUES (1, 'ADMIN');
INSERT INTO ROLE (ROLE_ID, ROLE) VALUES (2, 'USER');
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 2);
